language: go

dist: bionic
go:
- 1.15.x

before_script:
  - sudo apt-get -y install ninja-build
  
addons:
  apt:
    update: true

services:
  - docker

script:
  - docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
